name = "edge-worker-presentation"
account_id = "3e4f1532cfa5bc12d195b9683a04a823"

usage_model = "bundled"
compatibility_date = "2023-05-24"

workers_dev = false
main = "./dist/worker.js"
routes = [
	{ pattern = "edge.project-ignition.com", custom_domain = true },
]
kv_namespaces = [
  { binding = "KV", id = "fa2b150f47464113b22de76d93012dc5" }
]


[build]
command = ""
